# src/visualization/VizardInterface.jl

"""
Vizard interface for SpacecraftGames.jl

Converts trajectory data to Basilisk Vizard format for visualization.
Requires Basilisk to be installed separately.
"""
module VizardInterface

using LinearAlgebra
using StaticArrays
using ..BasiliskSetup  

export VizardScenario, write_vizard_file, visualize_with_vizard, run_vizard

"""
    VizardScenario

Container for Vizard visualization scenario data.
"""
struct VizardScenario
    spacecraft_data::Vector{Dict{String, Any}}
    time_data::Vector{Float64}
    settings::Dict{String, Any}
end

"""
    trajectory_to_vizard(trajectories::Vector{Trajectory{T}},
                         spacecraft_names::Vector{String};
                         reference_frame::Symbol=:LVLH) where T

Convert SpacecraftGames trajectories to Vizard format.

# Arguments
- `trajectories`: Vector of player trajectories
- `spacecraft_names`: Names for each spacecraft
- `reference_frame`: :LVLH or :ECI

# Returns
- `VizardScenario`: Data structure for Vizard visualization
"""
function trajectory_to_vizard(
    trajectories::Vector,
    spacecraft_names::Vector{String};
    reference_frame::Symbol=:LVLH
)
    
    @assert length(trajectories) == length(spacecraft_names) "Need name for each spacecraft"
    @assert all(t -> t.times == trajectories[1].times, trajectories) "All trajectories must share time points"
    
    times = trajectories[1].times
    n_players = length(trajectories)
    
    spacecraft_data = []
    
    for (i, traj) in enumerate(trajectories)
        # Extract position and attitude data
        n_times = length(times)
        
        positions = zeros(3, n_times)
        velocities = zeros(3, n_times)
        mrps = zeros(3, n_times)
        omega = zeros(3, n_times)
        
        for k in 1:n_times
            state = @view traj.states[:, k]
            
            # Position and velocity (always present)
            positions[:, k] = state[1:3]
            velocities[:, k] = state[4:6]
            
            # Attitude (if present)
            if length(state) >= 12
                mrps[:, k] = state[7:9]
                omega[:, k] = state[10:12]
            end
        end
        
        spacecraft_dict = Dict{String, Any}(
            "name" => spacecraft_names[i],
            "player_id" => traj.player_id,
            "position" => positions,  # 3 × N
            "velocity" => velocities,  # 3 × N
            "mrp" => mrps,             # 3 × N
            "omega" => omega,          # 3 × N
            "has_attitude" => length(traj.states[:, 1]) >= 12
        )
        
        push!(spacecraft_data, spacecraft_dict)
    end
    
    settings = Dict{String, Any}(
        "reference_frame" => String(reference_frame),
        "n_spacecraft" => n_players,
        "n_timesteps" => length(times),
        "dt" => length(times) > 1 ? times[2] - times[1] : 0.0
    )
    
    return VizardScenario(spacecraft_data, times, settings)
end

"""
    write_vizard_file(scenario::VizardScenario, output_file::String)

Write Vizard scenario to file in Basilisk-compatible format.

# Note
This creates a Python script that can be run with Basilisk's Vizard.
"""
function write_vizard_file(scenario::VizardScenario, output_file::String)
    
    if !endswith(output_file, ".py")
        output_file = output_file * ".py"
    end
    
    open(output_file, "w") do io
        write_vizard_python_script(io, scenario)
    end
    
    println("✓ Vizard script written to: $output_file")
    println("  Run with: python $output_file")
    
    return output_file
end

"""
    write_vizard_python_script(io::IO, scenario::VizardScenario)

Generate Python script for Basilisk Vizard.
"""
function write_vizard_python_script(io::IO, scenario::VizardScenario)
    
    println(io, "\"\"\"")
    println(io, "Spacecraft Formation Flying Visualization")
    println(io, "Generated by SpacecraftGames.jl")
    println(io, "\"\"\"")
    println(io, "")
    println(io, "import numpy as np")
    println(io, "from Basilisk.utilities import vizSupport")
    println(io, "from Basilisk.utilities import macros")
    println(io, "from Basilisk.utilities import SimulationBaseClass")
    println(io, "")
    
    # Write scenario data
    println(io, "# Scenario settings")
    println(io, "reference_frame = '$(scenario.settings["reference_frame"])'")
    println(io, "n_spacecraft = $(scenario.settings["n_spacecraft"])")
    println(io, "n_timesteps = $(scenario.settings["n_timesteps"])")
    println(io, "")
    
    # Write time data
    println(io, "# Time data")
    println(io, "times = np.array([")
    for (i, t) in enumerate(scenario.time_data)
        if i < length(scenario.time_data)
            println(io, "    $t,")
        else
            println(io, "    $t")
        end
    end
    println(io, "])")
    println(io, "")
    
    # Write spacecraft data
    for (i, sc_data) in enumerate(scenario.spacecraft_data)
        println(io, "# Spacecraft $(i): $(sc_data["name"])")
        
        # Position data
        println(io, "sc$(i)_position = np.array([")
        write_matrix_to_python(io, sc_data["position"])
        println(io, "]).T  # N × 3")
        println(io, "")
        
        # Velocity data
        println(io, "sc$(i)_velocity = np.array([")
        write_matrix_to_python(io, sc_data["velocity"])
        println(io, "]).T  # N × 3")
        println(io, "")
        
        if sc_data["has_attitude"]
            # MRP data
            println(io, "sc$(i)_mrp = np.array([")
            write_matrix_to_python(io, sc_data["mrp"])
            println(io, "]).T  # N × 3")
            println(io, "")
            
            # Angular velocity
            println(io, "sc$(i)_omega = np.array([")
            write_matrix_to_python(io, sc_data["omega"])
            println(io, "]).T  # N × 3")
            println(io, "")
        end
    end
    
    # Write Vizard setup code
    write_vizard_setup(io, scenario)
end

"""
    write_matrix_to_python(io::IO, mat::Matrix)

Write Julia matrix to Python numpy array format.
"""
function write_matrix_to_python(io::IO, mat::Matrix)
    n_rows, n_cols = size(mat)
    
    for i in 1:n_rows
        print(io, "    [")
        for j in 1:n_cols
            print(io, mat[i, j])
            if j < n_cols
                print(io, ", ")
            end
        end
        if i < n_rows
            println(io, "],")
        else
            println(io, "]")
        end
    end
end

"""
    write_vizard_setup(io::IO, scenario::VizardScenario)

Write Vizard initialization and animation code.
"""
function write_vizard_python_script(io::IO, scenario::VizardScenario)

    n_sc = scenario.settings["n_spacecraft"]

    # ---------- Python module docstring ----------
    println(io, "\"\"\"")
    println(io, "Spacecraft Formation Flying Visualization")
    println(io, "Generated by SpacecraftGames.jl")
    println(io, "\"\"\"")
    println(io, "")

    # ---------- Imports (top-level) ----------
    println(io, "import numpy as np")
    println(io, "")
    println(io, "# Try importing Basilisk with different possible paths")
    println(io, "try:")
    println(io, "    from Basilisk.utilities import vizSupport")
    println(io, "    from Basilisk.utilities import macros")
    println(io, "    from Basilisk.utilities import SimulationBaseClass")
    println(io, "    from Basilisk.simulation import spacecraft")
    println(io, "except ImportError:")
    println(io, "    print('Basilisk not found. Please install with: pip install bsk')")
    println(io, "    import sys")
    println(io, "    sys.exit(1)")
    println(io, "")

    # ---------- Python function ----------
    println(io, "def run_visualization():")
    println(io, "    # Scenario settings")
    println(io, "    reference_frame = '$(scenario.settings["reference_frame"])'")
    println(io, "    n_spacecraft = $(n_sc)")
    println(io, "    n_timesteps = $(scenario.settings["n_timesteps"])")
    println(io, "")

    # Create spacecraft objects
    for i in 1:n_sc
        sc_data = scenario.spacecraft_data[i]
        println(io, "    # Create spacecraft $i: $(sc_data["name"])")
        println(io, "    scObject$i = spacecraft.Spacecraft()")
        println(io, "    scObject$i.ModelTag = \"$(sc_data["name"])\"")
        println(io, "    scSim.AddModelToTask(simTaskName, scObject$i)")
        println(io, "")
    end

    # Data logging
    println(io, "    # Set up data logging")
    println(io, "    samplingTime = simulationTimeStep")
    for i in 1:n_sc
        println(io, "    scRec$i = scObject$i.scStateOutMsg.recorder(samplingTime)")
        println(io, "    scSim.AddModelToTask(simTaskName, scRec$i)")
    end
    println(io, "")

    # Enable Vizard
    println(io, "    # Enable Vizard visualization")
    println(io, "    viz = vizSupport.enableUnityVisualization(")
    println(io, "        scSim, simTaskName,")
    print(io, "        [")
    for i in 1:n_sc
        print(io, "scObject$i")
        if i < n_sc
            print(io, ", ")
        end
    end
    println(io, "],")
    println(io, "        saveFile=__file__")
    println(io, "    )")
    println(io, "")

    # Vizard settings
    println(io, "    # Configure Vizard settings")
    println(io, "    viz.settings.spacecraftSizeMultiplier = 10.0")
    println(io, "    viz.settings.showSpacecraftLabels = 1")
    println(io, "    viz.settings.orbitLinesOn = 1")
    println(io, "    viz.settings.showCelestialBodyLabels = 1")

    for i in 1:n_sc
        sc_data = scenario.spacecraft_data[i]
        println(io, "    viz.settings.spacecraftName.append(\"$(sc_data["name"])\")")
    end
    println(io, "")

    # Initial states
    println(io, "    # Set initial spacecraft states")
    for i in 1:n_sc
        println(io, "    scObject$i.hub.r_CN_NInit = [sc$(i)_position[0,0], sc$(i)_position[0,1], sc$(i)_position[0,2]]")
        println(io, "    scObject$i.hub.v_CN_NInit = [sc$(i)_velocity[0,0], sc$(i)_velocity[0,1], sc$(i)_velocity[0,2]]")

        sc_data = scenario.spacecraft_data[i]
        if sc_data["has_attitude"]
            println(io, "    scObject$i.hub.sigma_BNInit = [sc$(i)_mrp[0,0], sc$(i)_mrp[0,1], sc$(i)_mrp[0,2]]")
            println(io, "    scObject$i.hub.omega_BN_BInit = [sc$(i)_omega[0,0], sc$(i)_omega[0,1], sc$(i)_omega[0,2]]")
        end
    end
    println(io, "")

    # Simulation loop
    println(io, "    scSim.InitializeSimulation()")
    println(io, "    print('Running Basilisk simulation...')")
    println(io, "    for idx in range(1, len(times)):")
    for i in 1:n_sc
        println(io, "        scObject$i.hub.r_CN_NInit = [sc$(i)_position[idx,0], sc$(i)_position[idx,1], sc$(i)_position[idx,2]]")
        println(io, "        scObject$i.hub.v_CN_NInit = [sc$(i)_velocity[idx,0], sc$(i)_velocity[idx,1], sc$(i)_velocity[idx,2]]")

        sc_data = scenario.spacecraft_data[i]
        if sc_data["has_attitude"]
            println(io, "        scObject$i.hub.sigma_BNInit = [sc$(i)_mrp[idx,0], sc$(i)_mrp[idx,1], sc$(i)_mrp[idx,2]]")
            println(io, "        scObject$i.hub.omega_BN_BInit = [sc$(i)_omega[idx,0], sc$(i)_omega[idx,1], sc$(i)_omega[idx,2]]")
        end
    end
    println(io, "        scSim.ConfigureStopTime(macros.sec2nano(times[idx]))")
    println(io, "        scSim.ExecuteSimulation()")
    println(io, "")

    # ---------- Entry point ----------
    println(io, "if __name__ == '__main__':")
    println(io, "    run_visualization()")
end


"""
    visualize_with_vizard(trajectories::Vector,
                          output_file::String="vizard_scenario.py";
                          spacecraft_names::Vector{String}=String[],
                          run_immediately::Bool=false)

High-level function to visualize trajectories with Basilisk Vizard.

# Arguments
- `trajectories`: Vector of trajectories to visualize
- `output_file`: Output Python script filename
- `spacecraft_names`: Optional names for spacecraft
- `run_immediately`: If true, run the script immediately after generating

# Example
```julia
# Just generate script
visualize_with_vizard(trajectories, "my_formation.py")

# Generate and run
visualize_with_vizard(trajectories, "my_formation.py", run_immediately=true)
```
"""
function visualize_with_vizard(
    trajectories::Vector,
    output_file::String="vizard_scenario.py";
    spacecraft_names::Vector{String}=String[],
    run_immediately::Bool=false
)
    
    n_players = length(trajectories)
    
    # Generate default names if not provided
    if isempty(spacecraft_names)
        spacecraft_names = ["SC$i" for i in 1:n_players]
    end
    
    # Convert to Vizard format
    println("Converting trajectories to Vizard format...")
    scenario = trajectory_to_vizard(trajectories, spacecraft_names)
    
    # Write Python script
    println("Writing Vizard Python script...")
    script_path = write_vizard_file(scenario, output_file)
    
    println("\n" * "="^60)
    println("Vizard visualization script created!")
    println("="^60)
    println("\nScript: $script_path")
    
    if run_immediately
        println("\nRunning visualization...")
        run_vizard(script_path)
    else
        println("\nTo visualize:")
        println("  Option 1: run_vizard(\"$script_path\")")
        println("  Option 2: python $script_path  (requires Basilisk)")
    end
    
    println("="^60)
    
    return script_path
end

"""
    run_vizard(script_path::String; blocking::Bool=true)

Run a Vizard script. Automatically handles Basilisk installation.

# Arguments
- `script_path`: Path to Python script
- `blocking`: If true, wait for completion
"""
function run_vizard(script_path::String; blocking::Bool=true)
    BasiliskSetup.run_vizard_script(script_path, blocking=blocking)
end

end # module VizardInterface